@TM:1263972264
@N: BN225 :"":0:0:0:-1|Writing default property annotation file C:\Program Files\modeltech_6.5\examples\Tamrin\Arithmetic_Encoder\rev_1\Arithmetic_Encoder.map.
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF257 :"":0:0:0:-1|Gated clock conversion enabled 
@N: MF276 :"":0:0:0:-1|Gated clock conversion enabled, but no gated clocks found in design 
@N: MF333 :"":0:0:0:-1|Generated clock conversion enabled, but no generated clocks found in design 
@N: MT206 :"":0:0:0:-1|Autoconstrain Mode is ON
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@N: CD630 :"C:\Program Files\modeltech_6.5\examples\Tamrin\Arithmetic_Encoder\Arithmetic_Encoder_CR.vhd":5:7:5:31|M
@W: BN132 :"c:\program files\modeltech_6.5\examples\tamrin\arithmetic_encoder\arithmetic_encoder_cr.vhd":29:8:29:9|M
@N: CL201 :"C:\Program Files\modeltech_6.5\examples\Tamrin\Arithmetic_Encoder\Arithmetic_Encoder_CR.vhd":29:8:29:9|M
@N: CD630 :"C:\Program Files\modeltech_6.5\examples\Tamrin\Arithmetic_Encoder\Arithmetic_Encoder_DP.vhd":5:7:5:31|M
@N:  :"c:\program files\modeltech_6.5\examples\tamrin\arithmetic_encoder\arithmetic_encoder_dp.vhd":99:8:99:9|M
@N: FX404 :"c:\program files\modeltech_6.5\examples\tamrin\arithmetic_encoder\arithmetic_encoder_dp.vhd":168:10:168:11|M
@N:  :"C:\Program Files\modeltech_6.5\examples\Tamrin\Arithmetic_Encoder\Arithmetic_Encoder_TL.vhd":5:7:5:31|M
@N: CD630 :"C:\Program Files\modeltech_6.5\examples\Tamrin\Arithmetic_Encoder\Arithmetic_Encoder_TL.vhd":5:7:5:31|M
@N: CD630 :"C:\Program Files\modeltech_6.5\examples\Tamrin\Arithmetic_Encoder\Register_8bit_MD.vhd":5:7:5:26|M
@N: CD630 :"C:\Program Files\modeltech_6.5\examples\Tamrin\Arithmetic_Encoder\ROM_256x16bit_MD.vhd":5:7:5:26|M
@N: CL134 :"C:\Program Files\modeltech_6.5\examples\Tamrin\Arithmetic_Encoder\ROM_256x16bit_MD.vhd":22:15:22:17|M
@N: CD720 :"C:\Program Files\Synplicity\fpga_961\lib\vhd\std.vhd":123:18:123:21|M
